---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: "输入show cdp neighbors命令"
    ios_command:
      commands:
        - show cdp neighbors detail
    register: cdp_neighbors
  - name: "解析cdp_neighbors输出"
    set_fact:
      parsed_cdp_neighbor: "{{ cdp_neighbors.stdout[0] | parse_cli_textfsm('../templates/parse_cli/cisco_ios_show_cdp_neighbors_detail.template') }}"
  - name: "输出解析结果"
    debug:
      msg: "{{ parsed_cdp_neighbor }}"
