---
- hosts: '{{ hosts }}'
  connection: local
  tasks:
  - name: "show ip interface brief"
    ios_command:
      commands:
        - show ip interface brief
    register: intf_bri
  - name: "解析输出"
    include role:
      name: clay584.parse_genie
  - name: "格式化输出"
    debug:
      msg: "{{ intf_bri | parse_genie(command='show ip interface brief',os='ios')}}"
      
