---
- hosts: "{{ hosts }}"
  connection: local
  gather_facts: no
  tasks:
  - name: "运行命令"
    ios_command:
      commands:
        - show ip interface brief
    register: intf_bri
  - name: "解析输出"
    include_role:
      name: clay584.parse_genie

  - name: "格式化输出"
    debug:
      msg: "{{ intf_bri | parse_genie(command='show ip interface brief',os='ios')}}"
    delegate_to: localhost
